### ISSUE TITLE
EnableProjectionTransform return true at the end

### ISSUE THREAD

**Issue by dkollmann** [lensfun/lensfun#1506] opened 2021-11-17 18:27 UTC
In version 0.3.95 of lensfun, the function lfModifier::EnableProjectionTransform returns "true" at the end, unlike the other occasions where it returns "enabledMods".

**Comment by seebk** [comment] 2021-11-21 17:40
Duplicate of #1512, closing.

**Closed by seebk** 2021-11-21 17:40 UTC
