### ISSUE TITLE
Calibration files for Canon EF300mm f/2.8L IS USM +2x III

### ISSUE THREAD

**Issue by timsurber** [lensfun/lensfun#2188] opened 2024-03-15 19:43 UTC
Attached are the full calibration files for the Canon EF300mm f/2.8L IS USM with the 2x III extender.
If these files are good, I will also take for the calibration for 1.4x extender and without extender.
[lensfun_calibration.tar.gz](https://github.com/lensfun/lensfun/files/14620139/lensfun_calibration.tar.gz)

**Comment by tuxfanx** [comment] 2024-03-15 21:11
Two or three normal pictures would be helpful. The pictures can be uploaded [here](https://wilson.bronger.org/calibration).

**Comment by timsurber** [comment] 2024-03-15 21:14
Do you mean the test shot for vignetting/chromatic aberration or just some random pics taken with the lens? For what are they required?

**Comment by tuxfanx** [comment] 2024-03-15 21:46
Thanks for your answer!
Just some random pics or some shots for distortion/tca would be ok.
I need the pictures for testing purposes. I only merge profiles that I was able to test briefly. Unfortunately I could not find pictures on the internet.

**Comment by timsurber** [comment] 2024-03-15 22:08
I added the files!

**Comment by tuxfanx** [comment] 2024-03-17 16:35
Thanks for the pictures!
In the picture with the starry sky, it seems to me that the vignetting correction is not working completely. However, a slight undercorrection of the vignetting is always better than overcorrection and that would therefore not be a reason not to adopt your profile. Now, however, I only have this one picture to judge and my impression can be misleading.
You created your profile using Andreas Schneider's script. Maybe we should try to create a profile with Torsten Brongers script ["calibrate.py"](https://github.com/lensfun/lensfun/tree/master/tools/calibrate) again. I had a similar case before where T. Bronger's script produced better vignetting correction. If you want, I could do the creation. However, you would then have to upload your pictures for vignetting correction.
Unfortunately, the automatic lens detection doesn't work for me with darktable. Version 2 of the lens is recognized instead.
The lens was used with an adapter for the pics. I can't say whether that's the cause. In any case, there is a problem between darktable, exiv2 and lensfun in correct recognition that I couldn't solve.

**Comment by timsurber** [comment] 2024-03-19 23:00
Thank you for your feedback @tuxfanx 
I tried it again with the other script.
I applied Andreas Schneider's script (on the left) and Torsten Bronger's script (on the right). Then I increased the contrast on both images by the same amount significantly. 

![image](https://github.com/lensfun/lensfun/assets/138802321/716a9da8-a0ca-4000-96b9-cfb8e7563241)
What do you think works better?

It seems Torsten Bronger's script adjusts the corners better, the light top red corner is maybe some sort of glow from the sensor.
Lens Detection works for me with Rawtherapee. 
[flat_field_inf_5.6.zip](https://github.com/lensfun/lensfun/files/14657707/flat_field_inf_5.6.zip)
I attached the Flatfield Image for f5.6 and infinite focus.

**Comment by tuxfanx** [comment] 2024-03-20 14:17
@timsurber 
I merged the "bronger profile".

**Closed** 2024-03-20 14:17 UTC
