### ISSUE TITLE
Calibration upload 34df1d

### ISSUE THREAD

**Issue by bronger** [lensfun/lensfun#2211] opened 2024-04-12 17:06 UTC
Calibration images were uploaded to the directory that starts with “`34df1d_`”.

Please read the [workflow description](https://github.com/lensfun/lensfun/blob/master/tools/calibration_webserver/workflow.rst) for further instructions about the calibration.

Additional comments by the uploader:

> This is photo for distortion correction.
> I'm not sure if the image is full in focus (I'm not sure, if it matters for distortion).
> let me know if it's not good, then I will take another shot. I can't easily take another shot since I don't have this building near my house.

**Comment by jcubic** [comment] 2024-04-12 17:19
It's for Irix 11mm f/4 lens

**Comment by tuxfanx** [comment] 2024-04-13 10:00
Hi @jcubic,
Unfortunately, the lines in your photo have very little contrast and are a bit blurry. A precise positioning of points on the lines (magnification >100%) is therefore not possible.
We would appreciate it if you could send us a better picture. Please note the information as provided [here](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/) (section "Taking pictures).

**Comment by jcubic** [comment] 2024-04-13 11:40
Ok, I will try to create better picture. Unfortunately, I don't have another one of this exact spot, I have different ones, but they are not quite parallel to the camera. Next time I will pay more attention to see if the picture is in focus.

The problem is that with this lens almost all the time I use infinity as focus point. That's why I forget to check the focus.

**Comment by jcubic** [comment] 2024-04-13 11:41
You can close this, and I will upload again when I have a better picture.

**Closed** 2024-04-13 19:16 UTC
Labels: calibration request

**Comment by jcubic** [comment] 2024-04-25 16:21
Hey @tuxfanx, is this ok? I have this fence few meters of my house, so I can take it again. This is a manual lens, and it's hard to focus.

[![DSC_4453_02](https://github.com/lensfun/lensfun/assets/280241/c62ba88b-07a6-43d0-a02e-4cf71fe8ee43)](https://jcubic.pl/DSC_4453.jpg). There is even some purple fringing visible, so maybe it can also be used for Chromatic Aberration.

If it's ok, I will re-upload.

**Comment by tuxfanx** [comment] 2024-04-25 18:21
Hi @jcubic,
the image can be used for distortion correction. However, it is not suitable for a TCA correction.
For tca correction the sharpest possible images are important here. The image must contain high-contrast lines in horizontal and vertical directions from the center of the image to at least 2 corners of the image.
use the lowest real ISO of your camera sensor and the right aperture (read [here](https://pixls.us/articles/create-lens-calibration-data-for-lensfun/)).
