### ISSUE TITLE
Calibration upload 198fc0

### ISSUE THREAD

**Issue by bronger** [lensfun/lensfun#567] opened 2019-04-14 15:26 UTC
Calibration images were uploaded to the directory that starts with “`198fc0_`”.

Please read the [workflow description](https://github.com/lensfun/lensfun/blob/master/tools/calibration_webserver/workflow.rst) for further instructions about the calibration.

**Comment by Sturmflut** [comment] 2022-01-23 16:45
Images are for distortion and TCA, which already exist in the database.

Duplicate of #554

**Closed** 2022-01-23 17:02 UTC
Labels: calibration request, new profile
