### ISSUE TITLE
Calibration upload fa081c

### ISSUE THREAD

**Issue by bronger** [lensfun/lensfun#319] opened 2018-01-01 20:19 UTC
Calibration images were uploaded to the directory that starts with “`fa081c_`”.

Please read the [workflow description](https://github.com/lensfun/lensfun/blob/master/tools/calibration_webserver/workflow.rst) for further instructions about the calibration.

Additional comments by the uploader:

> I am not 100% sure if the buildings I used here are suitable as the line through the middle may not be 'strong' enough for you.
> 
> If they are not suitable if you could feedback what is wrong I will find another building and shoot again.
> 
> If they are suitable if you could confirm that too that would be great as I will return and shoot all my lenses as none of them are in the current lensfun database for the Pentax K-1 (1.0 crop factor) 
> 
> Thanks for your hardwork
> 
> John

**Comment by johnjbloomfield** [comment] 2018-01-02 19:41
I am the uploader

**Comment by junkyardsparkle** [comment] 2018-01-02 23:40
@johnjbloomfield The file server is very slow for me at the moment, so I only downloaded one of the files (0167) for now, but it looks good. This lens has very little distortion, so probably just the line at the top is sufficient. Normally having the 1/3 line where the wall meets the ground isn't ideal, but with metal-framed glass like that it should be ok. It gets harder to find good targets with wider lenses without getting too close. Since downloading the files is slow even at the best of times (for me, at least) it's best if you can limit the uploads to a single shot per focal length for distortion, and possibly again one per focal length for TCA if the distortion shots seem unsuitable (not enough corner detail/contrast, etc). The one image I looked at isn't ideal for TCA correction, but might work; like I said, I haven't seen the others yet.

It turns out there are quite a few recent uploads of FF pentax images, so you might want to check out [these issues](https://github.com/lensfun/lensfun/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+pentax+k1) and hold off on any that overlap your collection (as discussed on the mailing list) until someone evaluates those (hoping to catch up on this in the next week or so). Thanks for contributing to the effort!

**Comment by johnjbloomfield** [comment] 2018-01-03 08:41
@junkyardsparkle I've checked those issues and have no overlap.

Sorry for so many uploads they are all slightly different and two different buildings in fact just to try and get one right.

Feeling a bit more confident now I'll limit the uploads in future.

**Comment by junkyardsparkle** [comment] 2018-01-03 09:45
@johnjbloomfield As further feedback after looking at the rest of the images, I'll probably use 0173 for distortion calibration, simply because it has the line closest to the edge of the frame, and 0176 or 0177 for TCA, since they have high-contrast features. Image 0177 is a good example of a single image that could be used for both distortion and TCA, for future reference.

**Comment by johnjbloomfield** [comment] 2018-01-03 14:31
@junkyardsparkle thanks for the feedback I will get some more submitted as soon as I have time to go out and shoot them but I'll try to stick to 1/2 images per lens (focal length)

Were you ever able to find out if the tarball we discussed on the mailing list is being regularly updated by @bronger and how we can see when it has been updated?

**Comment by junkyardsparkle** [comment] 2018-01-04 03:35
No hurry, still some backlog to work through here. I was hoping the mailing list discussion about the packaged updates would provoke some input from those involved, but if there's no response there or here soon I'll resort to personal email.

**Comment by johnjbloomfield** [comment] 2018-01-04 12:50
@junkyardsparkle little bit of a hurry from my end as if the profiles aren't being made available in a way that I can update my software then I'll probably have to start using Adobe products (really don't want to) as it seems the commercial entities in charge of the software I use aren't pushing profile updates themselves.

There is also something quite wonderful about the fact I can help other photographers by just taking a few pictures and passing them along to someone else who is trying to help - so the 'romantic' in me really hopes the project is alive and kicking in the sense of being able to update my software too.

**Comment by junkyardsparkle** [comment] 2018-01-05 09:08
Ok, since this one was an easy job, I made the profile. You should get a copy emailed to you, but if this doesn't happen soon, let me know. This should give you some idea of how well your software handles the current format. The nice thing about the database is that it's consists of self-explanatory XML files that will always be useful to any developer who wants to implement them, unlike proprietary formats that can become unsupported on a whim. :)

**Comment by johnjbloomfield** [comment] 2018-01-05 13:14
@junkyardsparkle **Thank You** - I really appreciate your efforts.

I will look out for the email and try and install.

I have however been told by other ACDsee users that when they have tried to add individual profiles the software doesn't see them - it was only when replacing their current directory with the entire Tarball referenced earlier that they saw any change.

Keen to give it a go though! Will let you know how I get on.

**Comment by johnjbloomfield** [comment] 2018-01-05 20:41
@junkyardsparkle not yet had the email - where will it come from? so I can check my spam (which is a rather large folder)

**Comment by junkyardsparkle** [comment] 2018-01-05 21:47
It possibly may not be sent until the issue is closed (I don't run the server that handles that, not sure exactly how it's set up), and I don't want to close it yet. I'll mail you a copy shortly.

**Closed** 2018-01-11 23:02 UTC
Labels: calibration request
